[package]
name = "perfect_rand"
version = "0.1.0"
edition = "2021"
description = "A cipher for randomizing numbers in an arbitrary range."
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
